language: android
jdk:
- oraclejdk7

env:
  global:
    secure: N1sRQjwlExc51dA10dOvzdnkYMh9/X9WZmKwYqnWOguV+0dg3Jw2xXyBRxZLO1olIlIV0XGaI1HLAAO0OaFEYyWMO9BkZ60aJC8gePGnnwk1LSYR2moGAtlF6Y+aumfMZzXG4gU4QlVKbMd0uLvUWKu6eTqoMtVe+/C8GeJn6pk=

android:
  components:
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-license-.+'

before_script:
    - echo yes | android update sdk -u -a -t tools
    - echo yes | android update sdk -u -a -t build-tools-21.1.1,build-tools-21.0.1
    - echo yes | android update sdk -u -a -t android-21
    - echo yes | android update sdk -u -a -t extra-google-m2repository
    - echo yes | android update sdk -u -a -t extra-android-m2repository
    - echo yes | android update sdk -u -a -t extra-android-support,extra-google-google_play_services

script: ./gradlew clean build
after_success:
- chmod a+x .utility/push-javadoc-to-gh-pages.sh
- .utility/push-javadoc-to-gh-pages.sh